=== gematik/api-metadaten-repository/components/AnwendungsDiscovery/schemas/Backup/kim_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Anbieter": {
      "type": "string"
    },
    "Anwendung": {
      "type": "string"
    },
    "Version": {
      "type": "string"
    },
    "Services": {
      "type": "object",
      "properties": {
        "mailserver_pop3_uri": {
          "type": "string",
          "format": "uri"
        },
        "mailserver_smtp_uri": {
          "type": "string",
          "format": "uri"
        },
        "accmgnt_url": {
          "type": "string",
          "format": "uri"
        },
        "KAS_uri": {
          "type": "string",
          "format": "uri"
        },
        "LDAP_uri": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "mailserver_pop3_uri",
        "mailserver_smtp_uri",
        "accmgnt_url",
        "KAS_uri",
        "LDAP_uri"
      ]
    }
  },
  "required": ["Anbieter", "Anwendung", "Version", "Services"]
}

=== gematik/api-metadaten-repository/components/AnwendungsDiscovery/examples/Backup/example.json
{
  "Anbieter": "Akquinet",
  "Anwendung": "KIM",
  "Version": "1.5",
  "Services": {
    "mailserver_pop3_uri": "pop3://ms.akquinet.de:110",
    "mailserver_smtp_uri": "smtp://ms.akquinet.de:25",
    "accmgnt_url": "https://www.accmgnt.akquinet.de:8080",
    "KAS_uri": "https://www.kas.akquinet.de:8080",
    "LDAP_uri": "ldap://www.vzd.arvato.de/"
  }
}
